version: "3.8"

services:
  db:
    image: mongo:4.4-bionic
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}"
    volumes:
      - db-data:/data/db
    networks:
      - overlay
    ports:
      - 27017:27017

volumes:
  db-data:

networks:
  overlay:


